name: profile_tugas
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  video_player: ^2.9.5
  url_launcher: ^6.2.5
  image_picker: ^1.1.2
  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  fl_chart: ^0.68.0
  sqlite3_flutter_libs: ^0.5.0
  sqlite3: any
  path: any

  # Versi terbaru yang disarankan
  intl: ^0.20.2
  drift: ^2.34.0
  path_provider: ^2.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.12
  drift_dev: ^2.24.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/videos/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21